{% set name = "docparse" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/docparse-{{ version }}.tar.gz
  sha256: 3847946c36fb1176dfa895fc1448dffcf4b536a9936452d0652f820e8202e442

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - docparse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: 'https://github.com/jdidion/docparse'
  summary: 'Library to parse common python docstring formats.'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthdsm
